apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name: app
spec:
  containers:
  - name: app
    image: 540128513460.dkr.ecr.us-east-1.amazonaws.com/my_app:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DBHOST
      value: "mysql.project-2a.svc.cluster.local"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw123"
    - name: DBPORT
      value: "3306"

