apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysqlserver
  name: mysql
spec:
  containers:
  - name: mysql
    image: 540128513460.dkr.ecr.us-east-1.amazonaws.com/mysql_db:latest
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw123"
